yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страницы сообществ
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Публикации постов
    path('create/', views.post_create, name='post_create'),
    # Редактированиe постов
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """Модель для сообществ.

    Attributes:
        title: название группы.
        slug: уникальный адрес группы, часть URL
        description: описание сообщества.
    """

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    """Модель для хранения постов.

    Attributes:
        text: текст поста.
        pub_date: дата публикации поста.
        author: автор поста.
        group: возможность, при добавлении новой записи можно было сослаться
               на сообщество.
    """

    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        related_name='posts',
        blank=True, null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        # выводим текст поста
        return self.text

yatube/posts/forms.py
from .models import Post
from django.forms import ModelForm


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group, User
from .forms import PostForm
from typing import Any, Dict
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


ITEMS_PER_PAGE = 5


def index(request):
    """Главная страница."""
    posts = Post.objects.select_related('author').order_by('-pub_date')
    template = 'posts/index.html'
    paginator = Paginator(posts, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title: str = 'Последние обновления на сайте'
    context: Dict[str, Any] = {
        'posts': posts,
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Страницы сообществ."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("author").order_by('-pub_date')
    template = 'posts/group_list.html'
    paginator = Paginator(posts, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context: Dict[str, Any] = {
        'title': group.title,
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    profile_user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author__username=username)
    posts_counter = posts.count()
    fullname = request.user.get_full_name() if (
        request.user.is_authenticated) else ""
    paginator = Paginator(posts, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context: Dict[str, Any] = {
        'posts': posts,
        'profile_user': profile_user,
        'posts_counter': posts_counter,
        'page_obj': page_obj,
        'fullname ': fullname,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post_info = get_object_or_404(Post, pk=post_id)
    author_posts = post_info.author.posts.count()
    context: Dict[str, Any] = {
        'post_info': post_info,
        'author_posts': author_posts,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    title_new: str = 'Новый пост'
    if request.method == "POST":
        form = PostForm(request.POST)
        form.save(commit=False).author_id = request.user.pk
        if form.is_valid():
            form.save()
            return redirect('posts:profile', username=request.user)
    else:
        form = PostForm()

    context: Dict[str, Any] = {
        'title_new': title_new,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id, author=request.user)
    user_ = request.user.get_username()
    is_edit = True

    if request.method == 'GET':
        form = PostForm()
        if user_ != post.author.username:
            return redirect('posts:post_detail')

    elif request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts:profile', username=request.user)
    context = {
        'form': form,
        'post': post,
        'is_edit': is_edit,
    }
    return render(request, template, context)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}

{% block title %}
    {% if is_edit %}
        <title> Изменение поста </title>
    {% else %}
        <title> {{ title_new }} </title>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
            {% if is_edit %}
                <div class="card-header">
                    Изменение поста
                </div>
            {% else %}
                <div class="card-header">
                    Новый пост
                </div>
            {% endif %}
            <div class="card-body">
                <form method="POST"
                class="post-form"
                action=
                {% if is_edit %}
                    "{% url 'posts:post_edit' post.id %}">
                {% else %}
                    "{% url 'posts:post_create' %}">
                {% endif %}

                {% csrf_token %}

                {% for field in form %}

                <div class="form-group row my-3">
                {% if field.errors %}
                <div class= "alert alert-danger">
                    {{ field.errors }}
                </div>
                {% endif %}
                <label for="id_text">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                  {{ field|addclass:'form-control' }}
                </label>
                </div>
                {% endfor %}

                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                </div>

                </form>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  <title>{{title}}</title>
{% endblock %}

{% block group_description %}
  <div class="container">
    <p></p>
    <h2>{{group.title}}</h2>
    <h4>{{group.description}}</h4>
    <p></p>
  </div>
{% endblock %}

{% block content %}
{% for post in page_obj %}
  <div class="container">
    <article>
      <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
    <p>{{ post.text }}</p>
    </article>
  </div>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
    <title> {{ title }} </title>
{% endblock %}

{% block content %}
{% for post in page_obj %}
    <div class="container">
        <p></p>
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы</a>
        {% endif %}
    </div>
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    <title> Пост {{ post_info.text|truncatechars:30 }}</title>
{% endblock %}

{% block content %}
    <div class="row">
        <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
            Дата публикации: {{post_info.pub_date|date:"d E Y"}}
            </li>
            <!-- если у поста есть группа -->
            <li class="list-group-item">
            Группа: {{post_info.group.title}}
            {% if post_info.group %}
            <a href="{% url 'posts:group_list' post_info.group.slug %}">
                все записи группы
            </a>
            {% else%}
            <p>У данного текста нет группы.</p>
            {% endif %}
            </li>
            <li class="list-group-item">
            Автор: {{post_info.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: {{author_posts}}
            </li>
            <li class="list-group-item">
            <a href="{% url 'posts:profile' post_info.author.username %}">
                все посты пользователя
            </a>
            </li>
            {% if request.user.id == post_info.author.id %}
                <a class="btn btn-primary"
                href="{% url 'posts:post_edit' post_info.id %}">
                    редактировать запись
                </a>
            {% endif %}
        </ul>
        </aside>
        <article class="col-12 col-md-9">
        <p>{{ post_info.text }}</p>
        </article>
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
    <title> Профайл пользователя {{ profile_user.get_full_name }}</title>
{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Все посты пользователя {{ profile_user.get_full_name }}</h1>
        <h3>Всего постов: {{posts_counter}} </h3>
        {% for post in page_obj %}
            <div class="container">
                <p></p>
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>{{ post.text }}</p>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                        все записи группы</a>
                {% endif %}
            </div>
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
        <hr>
        <!-- Остальные посты. после последнего нет черты -->
        {% include 'includes/paginator.html' %}
    </div>


{% endblock %}